### ISSUE TITLE
HTML&CSS/Errors/Snakegame.html

### ISSUE THREAD

**Issue by faisal2203** [BVP-ISTE/HacktoberFest2021#11]
###Error

The following HTML file has errors in its tags/indentation /use of functions.

**Comment by wal33dahmad** [comment]
Can you assign this to me as well?

**Comment by faisal2203** [comment]
@wal33dahmad make a pull request , add me as a reviewer and link that pull request with this issue

**Comment by wal33dahmad** [comment]
@faisal2203 I've made a PR. Here is the link. https://github.com/BVP-ISTE/HacktoberFest2021/pull/326
I'm new to Opensource so in case I did something wrong, you can contact me at rana.waleed123@gmail.com
