### ISSUE TITLE
Python/Errors/max_freq.py

### ISSUE THREAD

**Issue by pratham2908** [BVP-ISTE/HacktoberFest2021#116]
## Error

# Maximum Frequency
You are given an array of integers that contain numbers in random
order. Write a program to find and return the number which occurs the
maximum times in the given input.
If two or more elements contend for the maximum frequency, return the element which occurs in the array first.

There are some errors in the program which disrupt it and doesn't give the desired output. Check and find them out

**Comment by Abhinav-CHD** [comment]
Hey, I would like to work on this issue

**Comment by shubhrastogi07** [comment]
Please assign this to me I would like to work on this issue
