### ISSUE TITLE
C++/Errors/PolynomialDirty.cpp 

### ISSUE THREAD

**Issue by divya520357** [BVP-ISTE/HacktoberFest2021#122]
The code solves a polynomial equation but has bugs.Rectify.

**Comment by sparsh0602** [comment]
I wanted to contribute to hacktoberfest 2021.
Plz assign me this issue.

I do alot of problem solving and also 3 star coder at codechef , so I will be able to do it.

**Comment by divya520357** [comment]
make a pull request , add me as a reviewer and link that pull request with this issue

**Comment by shubhrastogi07** [comment]
Can I work on this problem???
