### ISSUE TITLE
C++/Errors/UpperLowerDirty.cpp

### ISSUE THREAD

**Issue by divya520357** [BVP-ISTE/HacktoberFest2021#125]
The program contains the code to convert upper case string to lower case string using array but currently gives multiple errors. Rectify.

**Comment by Supratick2001** [comment]
Hey, I am a C++ programmer and also a participant in Hacktoberfest. Can you please assign this issue to me?

**Comment by Xav83** [comment]
Hi @divya520357,

I have create a Pull Request (#300), in order to solve this issue 😃 
Feel free to review it whenever you will have the time !

It seems that I can't add you as a reviewer of the Pull Request 🤔
