### ISSUE TITLE
C++/Errors/bubble sort dirty.cpp

### ISSUE THREAD

**Issue by divya520357** [BVP-ISTE/HacktoberFest2021#127]
The program implements the bubble sort algorithm but shows an error during implementation leading to an unordered output. Rectify.

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by divya520357** [comment]
@purohitmansi make a pull request , add me as a reviewer and link that pull request with this issue

**Comment by purohitmansi** [comment]
> @purohitmansi make a pull request , add me as a reviewer and link that pull request with this issue

I have made a PR regarding update bubble sort. Please do review this.

**Comment by purohitmansi** [comment]
> > @purohitmansi make a pull request , add me as a reviewer and link that pull request with this issue
> 
> I have made a PR regarding update bubble sort. Please do review this.

Please do checkout my PR.

**Comment by purohitmansi** [comment]
> > > @purohitmansi make a pull request , add me as a reviewer and link that pull request with this issue
> > 
> > 
> > I have made a PR regarding update bubble sort. Please do review this.
> 
> Please do checkout my PR.

@divya520357 I have made a new PR.
