### ISSUE TITLE
c++/errors/reverse_queue.cpp

### ISSUE THREAD

**Issue by divya520357** [BVP-ISTE/HacktoberFest2021#134]
find and correct the error in the while loop.

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by divya520357** [comment]
hey, @purohitmansi make a pull request , add me as a reviewer and link that pull request with this issue.

**Comment by purohitmansi** [comment]
Okayy

**Comment by purohitmansi** [comment]
> hey, @purohitmansi make a pull request, add me as a reviewer, and link that pull request with this issue.

I have made a PR. Please do check it.
