### ISSUE TITLE
C++/Errors/append array.c 

### ISSUE THREAD

**Issue by faisal2203** [BVP-ISTE/HacktoberFest2021#138]
There are some error in the code ,go through the code thoroughly and rectify the error.

**Comment by ArpitBirSingh** [comment]
I solve this issue. Can you view my pull request. #232

**Comment by purohitmansi** [comment]
Please do assign this to me. I would like to work on this.

**Comment by faisal2203** [comment]
@purohitmansi This issue is already solved. Please look into another issue.
