### ISSUE TITLE
C++/Errors/if sorted.c

### ISSUE THREAD

**Issue by faisal2203** [BVP-ISTE/HacktoberFest2021#140]
There are some error in the code ,go through the code thoroughly and rectify the error.

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by faisal2203** [comment]
make a pull request , add me as a reviewer and link that pull request with this issue

**Comment by Rupayan789** [comment]
Please assign this issue to me

**Comment by faisal2203** [comment]
@Rupayan789  make a pull request , add me as a reviewer and link that pull request with this issue

**Comment by strivercoder99** [comment]
I have fixed this issue. Please accept my PR.
