### ISSUE TITLE
C++/Errors/inserting in an array.c

### ISSUE THREAD

**Issue by faisal2203** [BVP-ISTE/HacktoberFest2021#141]
There are some error in the code ,go through the code thoroughly and rectify the error.

**Comment by purohitmansi** [comment]
Please do assign this to me. I would like to work on it in C++.

**Comment by faisal2203** [comment]
make a pull request , add me as a reviewer and link that pull request with this issue

**Comment by Aditya3403** [comment]
Sir I have made a Pull Request for rectifying errors in HTML, CSS and JS code . Kindly check  it and tell me the issue with it as it is not accepted. Thank You.

**Comment by Aditya3403** [comment]
https://github.com/Aditya3403/HacktoberFest2021 . It is named Rectified Errors . Thank You.
