### ISSUE TITLE
C++/Errors/sum of n-natural number.c

### ISSUE THREAD

**Issue by faisal2203** [BVP-ISTE/HacktoberFest2021#144]
There are some error in the code ,go through the code thoroughly and rectify the error.

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by faisal2203** [comment]
make a pull request , add me as a reviewer and link that pull request with this issue

**Comment by bhavuk-09** [comment]
Please do assign this to me. I would like to work on it 
.

**Comment by faisal2203** [comment]
@bhavuk-09  make a pull request , add me as a reviewer and link that pull request with this issue
