### ISSUE TITLE
C++/Tasks/printing linked list.cpp

### ISSUE THREAD

**Issue by faisal2203** [BVP-ISTE/HacktoberFest2021#145]
complete the code

**Comment by purohitmansi** [comment]
Please do assign this to me. I would like to work on it in C++.

**Comment by faisal2203** [comment]
make a pull request , add me as a reviewer and link that pull request with this issue

**Comment by purohitmansi** [comment]
Hey ! I am solving this. If I am not able to then you can till then please
do checkout for other one.

**Comment by purohitmansi** [comment]
> make a pull request , add me as a reviewer and link that pull request with this issue

I have made a PR. Please do review it.
