### ISSUE TITLE
C++/Tasks/SumTillSingle.cpp

### ISSUE THREAD

**Issue by faisal2203** [BVP-ISTE/HacktoberFest2021#148]
I could use some help to write a program for finding the sum of digits till single digit returns. :)

**Comment by bhavuk-09** [comment]
Please do assign this to me. I would like to work on it in C++.

**Comment by faisal2203** [comment]
make a pull request , add me as a reviewer and link that pull request with this issue

**Comment by vivekarora-02** [comment]
Hey, there!
I would like to contribute to this issue, can you please assign me?

ThankYou!

**Comment by faisal2203** [comment]
@vivekarora-02 Sorry this issue is already resolved. Please try another one.
