### ISSUE TITLE
C++/Tasks/power.cpp

### ISSUE THREAD

**Issue by faisal2203** [BVP-ISTE/HacktoberFest2021#152]
**Task**

Don't write main().
Don't read input, it is passed as function argument.
Return output and don't print it.
Taking input and printing output is handled automatically.

**Comment by purohitmansi** [comment]
Please do assign this to me. I would like to work on it in C++.

**Comment by faisal2203** [comment]
make a pull request , add me as a reviewer and link that pull request with this issue
