### ISSUE TITLE
Python/Tasks/calculate_the_power_of_number.py

### ISSUE THREAD

**Issue by pratham2908** [BVP-ISTE/HacktoberFest2021#169]
### Task
Write a Python program to calculate the value of 'a' to the power 'b'.
You are required to follow the template and fill in the missing pieces.

Some programs may have a few syntactic errors scattered here and there.

**Comment by ArpitBirSingh** [comment]
I solve this issue. Can you view my pull request. #286 
@pratham2908 
Thank You.
