### ISSUE TITLE
HTML&CSS/Errors/colorclock.html

### ISSUE THREAD

**Issue by faisal2203** [BVP-ISTE/HacktoberFest2021#17]
###Error

The following HTML file has errors in its tags/indentation /use of functions.

**Comment by faisal2203** [comment]
@wal33dahmad  make a pull request , add me as a reviewer and link that pull request with this issue

**Comment by wal33dahmad** [comment]
@faisal2203 check the PR here https://github.com/BVP-ISTE/HacktoberFest2021/pull/333 
Kindly add hacktoberfestaccepted label if accepted. In case of any issues please do let me know.
