### ISSUE TITLE
Python/Tasks/binary_numbers.py 

### ISSUE THREAD

**Issue by pratham2908** [BVP-ISTE/HacktoberFest2021#172]
### Task

Write a program which accepts a sequence of comma separated 4 digit binary numbers
as its input and then check whether they are divisible by 5 or not.
The numbers that are divisible by 5 are to be printed in a comma separated sequence.
Example:
0100,0011,1010,1001
Then the output should be:
1010

You are required to follow the template and fill in the missing pieces.
Some programs may have a few syntactic errors scattered here and there.

**Comment by And-Rahul** [comment]
Assign me .

**Comment by SohilK03** [comment]
Make PR's
