### ISSUE TITLE
HTML&CSS/Errors/color-change-on-hover-objects.html

### ISSUE THREAD

**Issue by faisal2203** [BVP-ISTE/HacktoberFest2021#18]
###Error

The following HTML file has errors in its tags/indentation /use of functions.

**Comment by purohitmansi** [comment]
Please do assign this to me. I would like to work on this.

**Comment by faisal2203** [comment]
make a pull request , add me as a reviewer and link that pull request with this issue

**Comment by ArpitBirSingh** [comment]
I solve this issue. Can you view my [pull request](https://github.com/BVP-ISTE/HacktoberFest2021/pull/228). #228
