### ISSUE TITLE
C++/Errors/Average.cpp

### ISSUE THREAD

**Issue by Shivam-999** [BVP-ISTE/HacktoberFest2021#21]
Error
There are some error in the code ,go through the code thoroughly and rectify the error.

**Comment by sparsh0602** [comment]
I wanted to contribute to hacktoberfest 2021.
Plz assign me this issue.

I do alot of problem solving and also 3 star coder at codechef , so I will be able to do it.

**Comment by purohitmansi** [comment]
Please do assign this to me. I would like to work on it in C++.
