### ISSUE TITLE
C++/Tasks/Reverse a linked list.cpp 

### ISSUE THREAD

**Issue by divya520357** [BVP-ISTE/HacktoberFest2021#31]
complete the while loop.

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by divya520357** [comment]
@purohitmansi make a pull request , add me as a reviewer and link that pull request with this issue

**Comment by archi15** [comment]
Hey @divya520357, can I work on this? Thanks!

**Comment by purohitmansi** [comment]
Hey! I am currently working on this. Please do checkout for other issues.

**Comment by purohitmansi** [comment]
@divya520357 I have made a PR. Please do check it out.
