### ISSUE TITLE
C++/Errors/reverse_stack.cpp

### ISSUE THREAD

**Issue by divya520357** [BVP-ISTE/HacktoberFest2021#45]
find and correct the error in the code.

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by divya520357** [comment]
@purohitmansi make a pull request , add me as a reviewer and link that pull request with this issue

**Comment by purohitmansi** [comment]
> @purohitmansi make a pull request , add me as a reviewer and link that pull request with this issue

I have made the PR. Do review it.
