### ISSUE TITLE
C++/Errors/Binary search.cpp

### ISSUE THREAD

**Issue by divya520357** [BVP-ISTE/HacktoberFest2021#60]
This code is used to perform the binary search and there are some error in the code.
go through the code thoroughly and rectify the error.
No need to change the main code.

**Comment by purohitmansi** [comment]
Please do assign this to me. I would like to work on it in C++.

**Comment by divya520357** [comment]
@purohitmansi make a pull request , add me as a reviewer and link that pull request with this issue

**Comment by Sonukumarkeshri4** [comment]
[https://github.com/BVP-ISTE/HacktoberFest2021/pull/194#issue-1014133298](url)

@purohitmansi Please review my PR.

**Comment by purohitmansi** [comment]
> @purohitmansi make a pull request , add me as a reviewer and link that pull request with this issue

I have made the PR. Please do check it.
