### ISSUE TITLE
Java/Errors/Quadratic expression errors.java

### ISSUE THREAD

**Issue by ShivamS2201** [BVP-ISTE/HacktoberFest2021#63]
It is the code for finding the roots of a quadratic equation.
There are some errors in the code. Go through the code and rectify them.
No need to change the main code.

**Comment by KholoodS** [comment]
Hello,
May I please know if  this issue still open to work upon?

**Comment by CinematicGenius007** [comment]
I already made the PR, please accept it. Thanks a lot for the oppurtunity.
